# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create([
                {:name => "Exclude", :display => false},
                {:name => "Flights", :display => true },
                {:name => "Cruises", :display => true},
                {:name => "Hotels", :display => true },
                {:name => "Packages", :display => true},
                {:name => "Rental Cars", :display => true},
                {:name => "Entertainment", :display => true}
                ])

ActiveRecord::Base.transaction do
  Deal.delete_all
  Feed.delete_all
end

feeds = Feed.create([
    {:url => "http://www.travelzoo.com/rss/all/" },
    {:url => "http://www.orbitz.com/rss/topdeals-vacationpackages.rss.xml" },
    {:url => "http://www.orbitz.com/rss/lowestpackages.rss.xml"},
    {:url => "http://www.orbitz.com/rss/topdeals-hotels.rss.xml"},
    {:url => "http://www.orbitz.com/rss/hotelpromos.rss.xml"},
    {:url => "http://www.orbitz.com/rss/HotelsUnder99.rss.xml"},
    {:url => "http://www.orbitz.com/rss/topdeals-flights.rss.xml"},
    {:url => "http://www.orbitz.com/rss/flightdeals.rss.xml"},
    {:url => "http://www.orbitz.com/rss/flightdealsByDestinations.rss.xml"},
    {:url => "http://www.orbitz.com/rss/cardeals.rss.xml"},
    {:url => "http://www.orbitz.com/rss/cruises.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/NV/LasVegas.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/NY/NewYork.rss.xml"},
    {:url => "http://www.orbitz.com/rss/MX/Cancun.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/FL/Orlando.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/CA/LosAngeles.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/FL/Miami.rss.xml"},
    {:url => "http://www.orbitz.com/rss/BS/Nassau.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/IL/Chicago.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/CA/SanFrancisco.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/CO/Denver.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/GA/Atlanta.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/AZ/Phoenix.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/HI/Honolulu(IslandofOahu).rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/MA/Boston.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/WA/Seattle.rss.xml"},
    {:url => "http://www.orbitz.com/rss/US/DC/WashingtonDC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/LAS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/JFK.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/CUN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/MCO.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/LAX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/MIA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/NAS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/MDW.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/SFO.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/DEN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/PHX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/HNL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/BOS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/SEA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/IAD.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/BOS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/BWI.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/CLT.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/CMH.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/CHI.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/DEN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/DAL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/DTT.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/FLL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/HOU.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/IND.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/MKC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/LOS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/LAX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/MIA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/MSP.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/EWR.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ORL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/PHL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/PHX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/PIT.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/PDX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/RDL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/SLC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/SAN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/SJC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/SEA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/TPA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/origin/WAS.rss.xml"},

    {:url => "http://www.orbitz.com/rss/packages/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/BOS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/BWI.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/CLT.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/CMH.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/DEN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/FLL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/HOU.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/IND.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/LAS.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/LAX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/MIA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/MSP.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/EWR.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/PHL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/PHX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/PIT.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/PDX.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/RDL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/SLC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/SAN.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/ATL.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/SJC.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/SEA.rss.xml"},
    {:url => "http://www.orbitz.com/rss/packages/origin/TPA.rss.xml"}  ,

    {:url => "http://www.cheaptickets.com/rss/topdeals-flights.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/flightdeals.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/flightdealsByDestinations.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/topdeals-vacationpackages.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/lowestpackages_under500.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/lowestpackages_over500.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/topdeals-hotels.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/hotelpromos.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/HotelsUnder99.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/cardeals.rss.xml"},
    {:url => "http://www.cheaptickets.com/rss/cruises.rss.xml"}
])


feeds.each do |f|
  f.fetch
end